export const testTiles = {
  bridgeEast: "./tiles/bridgeEast.png",
  bridgeNorth: "./tiles/bridgeNorth.png",
  crossroad: "./tiles/crossroad.png",
  dirtHigh: "./tiles/dirtHigh.png",
  dirt: "./tiles/dirt.png",
  grass: "./tiles/grass.png",
  hillCornerEast: "./tiles/hillCornerEast.png",
  hillCornerNW: "./tiles/hillCornerNW.png",
  hillCornerSE: "./tiles/hillCornerSE.png",
  hillCornerWest: "./tiles/hillCornerWest.png",
  hillEast: "./tiles/hillEast.png",
  hillNorth: "./tiles/hillNorth.png",
  hillRoadEast: "./tiles/hillRoadEast.png",
  hillRoadNorth: "./tiles/hillRoadNorth.png",
  hillRoadSouth: "./tiles/hillRoadSouth.png",
  hillRoadWest: "./tiles/hillRoadWest.png",
  hillSouth: "./tiles/hillSouth.png",
  hillWest: "./tiles/hillWest.png",
  lotCornerEast: "./tiles/lotCornerEast.png",
  lotCornerNorth: "./tiles/lotCornerNorth.png",
  lotCornerSouth: "./tiles/lotCornerSouth.png",
  lotCornerWest: "./tiles/lotCornerWest.png",
  lotEast: "./tiles/lotEast.png",
  lotExitEast: "./tiles/lotExitEast.png",
  lotExitNorth: "./tiles/lotExitNorth.png",
  lotExitSouth: "./tiles/lotExitSouth.png",
  lotExitWest: "./tiles/lotExitWest.png",
  lotNorth: "./tiles/lotNorth.png",
  lotPark: "./tiles/lotPark.png",
  lot: "./tiles/lot.png",
  lotSouth: "./tiles/lotSouth.png",
  lotWest: "./tiles/lotWest.png",
  roadCornerES: "./tiles/roadCornerES.png",
  roadCornerNE: "./tiles/roadCornerNE.png",
  roadCornerNW: "./tiles/roadCornerNW.png",
  roadCornerWS: "./tiles/roadCornerWS.png",
  roadEast: "./tiles/roadEast.png",
  roadEndEast: "./tiles/roadEndEast.png",
  roadEndNorth: "./tiles/roadEndNorth.png",
  roadEndSouth: "./tiles/roadEndSouth.png",
  roadEndWest: "./tiles/roadEndWest.png",
  roadNorth: "./tiles/roadNorth.png",
  roadTEast: "./tiles/roadTEast.png",
  roadTNorth: "./tiles/roadTNorth.png",
  roadTSouth: "./tiles/roadTSouth.png",
  roadTWest: "./tiles/roadTWest.png",
  treeConiferShort: "./tiles/treeConiferShort.png",
  treeConiferTall: "./tiles/treeConiferTall.png",
  treeShort_autumn: "./tiles/treeShort_autumn.png",
  treeShort: "./tiles/treeShort.png",
  treeTall_autumn: "./tiles/treeTall_autumn.png",
  treeTall: "./tiles/treeTall.png",
  waterBeachCornerEast: "./tiles/waterBeachCornerEast.png",
  waterBeachCornerNorth: "./tiles/waterBeachCornerNorth.png",
  waterBeachCornerSouth: "./tiles/waterBeachCornerSouth.png",
  waterBeachCornerWest: "./tiles/waterBeachCornerWest.png",
  waterBeachEast: "./tiles/waterBeachEast.png",
  waterBeachNorth: "./tiles/waterBeachNorth.png",
  waterBeachSouth: "./tiles/waterBeachSouth.png",
  waterBeachWest: "./tiles/waterBeachWest.png",
  waterCornerEast: "./tiles/waterCornerEast.png",
  waterCornerNorth: "./tiles/waterCornerNorth.png",
  waterCornerSouth: "./tiles/waterCornerSouth.png",
  waterCornerWest: "./tiles/waterCornerWest.png",
  waterEast: "./tiles/waterEast.png",
  waterNorth: "./tiles/waterNorth.png",
  water: "./tiles/water.png",
  waterSouth: "./tiles/waterSouth.png",
  waterWest: "./tiles/waterWest.png"
};

export const testMap = [
  [
    "grass",
    "grass",
    "grass",
    "grass",
    "grass",
    "grass",
    "grass",
    "grass",
    "grass",
    "grass",
    "grass",
    "grass",
    "grass",
    "grass",
    "grass"
  ],
  [
    "grass",
    "grass",
    "grass",
    "grass",
    "grass",
    "grass",
    "grass",
    "grass",
    "grass",
    "grass",
    "grass",
    "grass",
    "grass",
    "grass",
    "grass"
  ],
  [
    "grass",
    "grass",
    "grass",
    "grass",
    "grass",
    "grass",
    "grass",
    "grass",
    "grass",
    "grass",
    "grass",
    "grass",
    "grass",
    "grass",
    "grass"
  ],
  [
    "grass",
    "grass",
    "grass",
    "grass",
    "grass",
    "grass",
    "grass",
    "grass",
    "grass",
    "grass",
    "grass",
    "grass",
    "grass",
    "grass",
    "grass"
  ],
  [
    "grass",
    "grass",
    "grass",
    "grass",
    "grass",
    "grass",
    "grass",
    "grass",
    "grass",
    "grass",
    "grass",
    "grass",
    "grass",
    "grass",
    "grass"
  ],
  [
    "grass",
    "grass",
    "grass",
    "grass",
    "grass",
    "grass",
    "grass",
    "grass",
    "grass",
    "grass",
    "grass",
    "grass",
    "grass",
    "grass",
    "grass"
  ],
  [
    "grass",
    "grass",
    "grass",
    "grass",
    "grass",
    "grass",
    "grass",
    "grass",
    "grass",
    "grass",
    "grass",
    "grass",
    "grass",
    "grass",
    "grass"
  ],
  [
    "grass",
    "grass",
    "grass",
    "grass",
    "grass",
    "grass",
    "grass",
    "grass",
    "grass",
    "grass",
    "grass",
    "grass",
    "grass",
    "grass",
    "grass"
  ],
  [
    "grass",
    "grass",
    "grass",
    "grass",
    "grass",
    "grass",
    "grass",
    "grass",
    "grass",
    "grass",
    "grass",
    "grass",
    "grass",
    "grass",
    "grass"
  ],
  [
    "grass",
    "grass",
    "grass",
    "grass",
    "grass",
    "grass",
    "grass",
    "grass",
    "grass",
    "grass",
    "grass",
    "grass",
    "grass",
    "grass",
    "grass"
  ],
  [
    "grass",
    "grass",
    "grass",
    "grass",
    "grass",
    "grass",
    "grass",
    "grass",
    "grass",
    "grass",
    "grass",
    "grass",
    "grass",
    "grass",
    "grass"
  ],
  [
    "grass",
    "grass",
    "grass",
    "grass",
    "grass",
    "grass",
    "grass",
    "grass",
    "grass",
    "grass",
    "grass",
    "grass",
    "grass",
    "grass",
    "grass"
  ],
  [
    "grass",
    "grass",
    "grass",
    "grass",
    "grass",
    "grass",
    "grass",
    "grass",
    "grass",
    "grass",
    "grass",
    "grass",
    "grass",
    "grass",
    "grass"
  ],
  [
    "grass",
    "grass",
    "grass",
    "grass",
    "grass",
    "grass",
    "grass",
    "grass",
    "grass",
    "grass",
    "grass",
    "grass",
    "grass",
    "grass",
    "grass"
  ],
  [
    "grass",
    "grass",
    "grass",
    "grass",
    "grass",
    "grass",
    "grass",
    "grass",
    "grass",
    "grass",
    "grass",
    "grass",
    "grass",
    "grass",
    "grass"
  ]
];
